{'do_train': True, 'do_test': False, 'do_predict': False, 'train_data_path': './sample_data/train.tsv', 'eval_data_path': './sample_data/test.tsv', 'input_file': None, 'output_file': None, 'use_bert': True, 'use_zen': False, 'bert_model': 'C:/Program Files/Git/path/to/bert/model', 'eval_model': None, 'cache_dir': '', 'max_seq_length': 300, 'max_ngram_size': 300, 'do_lower_case': False, 'train_batch_size': 2, 'eval_batch_size': 2, 'learning_rate': 5e-05, 'num_train_epochs': 3.0, 'warmup_proportion': 0.1, 'no_cuda': False, 'local_rank': -1, 'seed': 42, 'gradient_accumulation_steps': 1, 'fp16': False, 'loss_scale': 0, 'server_ip': '', 'server_port': '', 'patient': 10, 'ngram_num_threshold': 2, 'av_threshold': 2, 'max_ngram_length': 5, 'model_name': 'sample_model', 'use_memory': True, 'decoder': 'crf', 'ngram_flag': 'av', 'save_top': 1}
device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "wmseg_main.py", line 677, in <module>
    main()
  File "wmseg_main.py", line 667, in main
    train(args)
  File "wmseg_main.py", line 82, in train
    word2id = get_word2id(args.train_data_path)
  File "C:\Users\Asus\Desktop\NLP\WMSeg\wmseg_helper.py", line 350, in get_word2id
    for line in open(train_data_path):
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8: character maps to <undefined>
device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "wmseg_main.py", line 677, in <module>
    main()
  File "wmseg_main.py", line 669, in main
    test(args)
  File "wmseg_main.py", line 374, in test
    seg_model_checkpoint = torch.load(args.eval_model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/model_name/model.pt'
device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "wmseg_main.py", line 677, in <module>
    main()
  File "wmseg_main.py", line 671, in main
    predict(args)
  File "wmseg_main.py", line 475, in predict
    seg_model_checkpoint = torch.load(args.eval_model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/model_name/model.pt'
